import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import ModalProvider from "./components/modals/Provider";
import NavBar from "./components/NavBar";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col ${roboto.className}`}>
        <ModalProvider>
          <NavBar />
          <main className="flex-1 w-fullflex">{children}</main>
          <Footer />
        </ModalProvider>
      </body>
    </html>
  );
}
